apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: frontend-alerts
  namespace: monitoring
spec:
  groups:
  - name: frontend
    rules:
    - alert: HighErrorRate
      expr: rate(frontend_errors_total[5m]) > 0.01
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: High frontend error rate
        description: Error rate is above 1% for 5 minutes

    - alert: SlowPageLoad
      expr: histogram_quantile(0.95, sum(rate(page_load_time_bucket[5m])) by (le)) > 3
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: Slow page load times
        description: 95th percentile page load time is above 3 seconds

    - alert: HighMemoryUsage
      expr: container_memory_usage_bytes{container="react-app"} > 256 * 1024 * 1024
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: High memory usage
        description: Container memory usage is above 256MB